// GENERATED by tools/import-hero-sheet.mjs — do not edit by hand.
// Placeholder: zero frames, so the renderer uses its vector-fallback hero
// (the standing per-entity-swap rule). Run the importer on a sprite sheet
// to populate:  node tools/import-hero-sheet.mjs art/hero-sheet.png
export interface HeroSheetFrame {
  w: number;
  h: number;
  data: (string | null)[];
}
export const HERO_SHEET_FRAMES: HeroSheetFrame[] = [];
