// GENERATED by tools/import-hero-sheet.mjs — do not edit by hand.
// Placeholder: zero frames, so the renderer uses its vector-fallback hero
// (the standing per-entity-swap rule). Run the importer on a sprite sheet
// to populate:  node tools/import-hero-sheet.mjs art/hero-sheet.png
export interface HeroSheetFrame {
  w: number;
  h: number;
  data: (string | null)[];
}
export const HERO_SHEET_FRAMES: HeroSheetFrame[] = [];
// 8-direction standing set, indexed by the canonical octant
// (0=E,1=SE,2=S,3=SW,4=W,5=NW,6=N,7=NE — matches Game's dir derivation).
export const HERO_SHEET_DIRS: HeroSheetFrame[] = [];
